### PR TITLE
Add a pre-commit configuration file.

### PR DESCRIPTION
**Pull request by wvreeven**

### CODE REVIEW

**Review by r-owen — COMMENTED** [review]
Why is this package missing a tests directory and a Jenkinsfile? I realize that's out of scope for this particular ticket, but it'd still be useful to fix.

**Comment by r-owen** [comment]
I added tests/test_config_files in branch  `u/rowen/add_tests`. Feel free to cherry-pick it if you like. The results of running it:
* CBP: some config files are not valid
* LinearStage: I don't have all required package so I don't know if all files pass
* TunableLaser: all files pass

I only added that one dir and file; I did not add Jenkinsfile

**Review by r-owen — CHANGES_REQUESTED** [review]
Please add unit tests and fix broken config files. We could consider making that a separate PR but I'd be a lot more comfortable not letting this slide any further.

**Comment by wvreeven** [comment]
Closing this branch and PR since this was solved in another branch and PR.

**Pull request closed without merging**
